version: '3.5'

services:

  postgresql:
    image: postgres:14-bullseye
    container_name: postgresql_container
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-s3cr3t}
    volumes:
       - postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./import:/var/lib/pgadmin/storage/import
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
    postgres:
    pgadmin: